import pathlib

# Remove .fzn, .info, .infor, and .minion files generated by Savile Row
def cleanup(stage):
    base = str(stage.PARAM)

    for ext in [".fzn", ".info", ".infor", ".minion"]:
        path = pathlib.Path(base + ext)
        path.unlink(missing_ok=True)